# Created by github.com/alexandzors 01-29-2019
# Copy this file into a dir and run "docker compose -f ombi_docker-compose.yml up"

version: '3'
services:
  ombi:
    deploy:
      replicas: 1
    image: linuxserver/ombi:latest
    volumes:
      /path/on/host:/config
    environment:
      TZ: America/New_York
    ports:
      3579:3579
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://<ipofservice>:3579 || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3    