# THIS COMPOSE FILE IS IN DEVELOPMENT. DO NOT USE.
version: '3'
services:
  database:
    deploy:
      replicas: 1
    image: mysql
    volumes:
      pagekitdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
      MYSQL_DATABASE: pagekit

  pagekit:
    deploy:
      replicas: 1
    image: ubermuda/pagekit
    links:
      - database
    ports:
      - "30080:80"
    volumes:
      pagekit:/pagekit/

volumes:
  pagekitdb:
  pagekit:
