# Created by github.com/alexandzors 01-04-2019
# Copy this file into a dir and run "docker-compose -f phlex_docker-compose.yml up"

version: '3'
services:
  phlex:
    image: digitalhigh/phlex
    ports:
      - "5666:80"
      - "5667:443"
    volumes:
      - /path/on/host:/config
    environment:
      - TZ=America/New_York
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://<ipofservice>:5666 || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3    