# Change "<LOCALNET>" (ie 192.168.1.0/24) to match your network that the docker machine is connected to under "transmission-openvpn"
# Change  "<USERNAME>" and "<PASSWORD>" to your PIA vpn login info (Can use app logins from your user account).
#
# Created by github.com/alexandzors 01-06-2019
# See github.com/haugene/transmission-openvpn for all environment variables.
# Do to limitations in docker swarm, and priviledged permissions, this compose file can not be used to deploy this image as a swarm service/container.
# Copy this file into a dir and run "docker compose -f transmission_docker-compose.yml up" to deploy this container. 
version: "3"
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    environment:
      PGID: "1000"
      PUID: "1000"
      log-driver: "json-file"
      log-opt: "max-size=10m"
      dns: "1.1.1.1"
      OPENVPN_PROVIDER: PIA
      LOCAL_NETWORK: "<LOCALNET>"
      OPENVPN_CONFIG: "CA Toronto,CA Montreal"
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      OPENVPN_USERNAME: "<USERNAME>"
      OPENVPN_PASSWORD: "<PASSWORD>"
      TRANSMISSION_DOWNLOAD_DIR: "/downloads/complete"
      TRANSMISSION_INCOMPLETE_DIR: "/downloads/incomplete"
      TRANSMISSION_RATIO_LIMIT: ".01"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_WEB_UI: "combustion"
      TRANSMISSION_BLOCKLIST_URL: "http://john.bitsurge.net/public/biglist.p2p.gz"
      WEBPROXY_ENABLED: "true"
      WEBPROXY_PORT: "9092"
    image: haugene/transmission-openvpn:latest
    ports:
      - "9091:9091"
      - "9092:9092"
    volumes:
      - transmission-dl:/downloads
      - transmission-cfg:/config
      - "/etc/localtime:/etc/localtime:ro"
      - transmission-data:/data
     
volumes:
 transmission-cfg:
 transmission-data:
 transmission-dl:
  - /path/on/host