# This file deploys the Ubiquiti Unifi controller as a docker stack based off of the linuxserver.io unifi image.
#
# Created by github.com/alexandzors 11-9-2018
#
# Run this by coping this file into a folder and using "docker-compose -f unifi_docker-compose.yml up"
#
version: "3"
services:
  unifi:
    image: linuxserver/unifi:latest
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080/tcp"
      - "8883:8883/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "6789:6789/tcp"
      - "1900:1900/udp"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - unifi_data:/config

volumes:
  unifi_data: