# Change the volume for /logs source to your plex server's shared logs folder otherwise tautulli won't work. This file defaults to a cifs mounted directory in /media/plexlogs
# Change volume sources to match your setup.
#
# Created by github.com/alexandzors 01-08-2019
# Copy this file into a dir and run "docker stack deploy -c tautulli_docker-compose.yml plex"
version: '3'
services:
  tautulli:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 240s
    image: linuxserver/tautulli
    ports:
      - "8181:8181"
    environment:
     - PGID=1000
     - PUID=1000
     - TZ=America/New_York
    volumes:
      - "/path/on/host:/config"
      - "/path/on/host:/logs:ro"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://<ipofservice>:8181 || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3    